// Generated by purrc — do not edit.
// cheatah-deps: parsers socket string tls
#pragma once
#include "cheatah.hpp"
#include "parsers.hpp"
#include "socket.hpp"
#include "string.hpp"
#include "tls.hpp"

/**
 * @file requests.hpp
 *
 * requests — HTTP for cheatah, in the spirit of Python's requests. THE FIRST STANDARD-LIBRARY
 * MODULE WRITTEN IN PURE CHEATAH (.purr): all protocol logic below is cheatah source, compiled
 * by purrc into an importable module. It rides on the C++-authored stdlib underneath —
 * `socket` for TCP and `parsers.url` for URL parsing.
 *
 * v1.1 speaks HTTP/1.1 over plain TCP, one connection per request (`Connection: close`):
 *   let r = requests.get("http://host:port/path")
 *   let o = Options({.timeout_ms = 5000})
 *   o.params["symbol"] = "SPX"
 *   let q = requests.get(url, o)
 *   if q.ok() { io.print(q.body) }
 * Covers: query params (percent-encoded), custom headers, Content-Length / chunked /
 * close-delimited body framing, redirect following, per-request timeouts, response headers
 * (case-insensitive via lowercased keys), and `https://` through the cheatah `tls` module —
 * a from-scratch TLS 1.3 client over the cheatah crypto modules (x25519, aead, hashlib HKDF;
 * no OpenSSL). The tls module REFUSES servers it cannot authenticate (see tls.hpp).
 */
namespace cheatah::requests {

namespace builtins = ::cheatah::builtins;
namespace parsers = ::cheatah::parsers;
namespace socket = ::cheatah::socket;
namespace string = ::cheatah::string;
namespace tls = ::cheatah::tls;

/**
 * Per-request options.
 *
 * Unset fields take the documented defaults at request time: `timeout_ms <= 0` -> 30000,
 * `max_redirects <= 0` -> 5. `params` are appended to the request-target percent-encoded;
 * `headers` are sent verbatim (a User-Agent is added unless one is given).
 * @systest RequestsSys.QueryParams
 * @systest RequestsSys.CustomHeaders
 */
struct Options {
    /**
     * Query parameters appended to the request-target, percent-encoded (name -> value).
     */
    std::unordered_map<std::string, std::string> params;
    /**
     * Extra request headers sent verbatim (a default User-Agent is added unless one is given).
     */
    std::unordered_map<std::string, std::string> headers;
    /**
     * Per-request timeout in milliseconds; <= 0 uses the 30000 ms default.
     */
    long long timeout_ms;
    /**
     * Maximum number of 3xx redirects to follow; <= 0 uses the default of 5.
     */
    long long max_redirects;
};

/**
 * The outcome of one request.
 *
 * `error` distinguishes transport failures (DNS, refused, timeout, malformed URL/response)
 * from HTTP-level failures: a 404 is a COMPLETED exchange — ok() is false but error stays
 * "" and status/headers/body are real. Header names are stored LOWERCASED, so header()
 * lookup is case-insensitive (RFC 9110).
 * @systest RequestsSys.NotFound
 * @systest RequestsSys.ErrorPaths
 */
struct Response {
    /**
     * HTTP status code (e.g. 200, 404); 0 when the request never completed (see `error`).
     */
    long long status;
    /**
     * Response headers, with LOWERCASED names for case-insensitive lookup (use `header()`).
     */
    std::unordered_map<std::string, std::string> headers;
    /**
     * The response body bytes (decoded from chunked/Content-Length framing).
     */
    std::string body;
    /**
     * The final URL the response came from (after following any redirects).
     */
    std::string url;
    /**
     * Transport-level error message (DNS/connect/timeout/TLS/malformed); "" on a completed
     * exchange, including a non-2xx HTTP status.
     */
    std::string error;
    /**
     * Whether the exchange completed with a 2xx status.
     *
     * @return true iff `error` is empty and `status` is in [200, 300).
     * @complexity O(1).
     * @alloc none.
     * @systest RequestsSys.BasicGet
     */
    auto ok() const {
        return ((((*this).error == std::string("")) && ((*this).status >= 200LL)) && ((*this).status < 300LL));
    }
    /**
     * Case-insensitive response-header lookup.
     *
     * @param name header name, any capitalization (`"Content-Type"` == `"content-type"`).
     * @return the header's value, or "" when the response did not carry it.
     * @complexity O(1) average (one hash lookup).
     * @alloc allocates the lowercased key.
     * @systest RequestsSys.HeaderLookup
     */
    auto header(builtins::Value auto&& name) const {
        auto key = string::lower(name);
        if (builtins::contains((*this).headers, key)) {
            return builtins::index((*this).headers, key);
        }
        return std::string("");
    }
};

}  // namespace cheatah::requests (paused for JSON schema synthesis)
namespace cheatah::parsers::json {
/** JSON schema for `Options`, synthesized by purrc from the struct's fields — powers `parsers.json.read` into this type. */
template <> inline constexpr auto schema<::cheatah::requests::Options> = object(field("params", &::cheatah::requests::Options::params), field("headers", &::cheatah::requests::Options::headers), field("timeout_ms", &::cheatah::requests::Options::timeout_ms), field("max_redirects", &::cheatah::requests::Options::max_redirects));
/** JSON schema for `Response`, synthesized by purrc from the struct's fields — powers `parsers.json.read` into this type. */
template <> inline constexpr auto schema<::cheatah::requests::Response> = object(field("status", &::cheatah::requests::Response::status), field("headers", &::cheatah::requests::Response::headers), field("body", &::cheatah::requests::Response::body), field("url", &::cheatah::requests::Response::url), field("error", &::cheatah::requests::Response::error));
}  // namespace cheatah::parsers::json
namespace cheatah::requests {

/**
 * Percent-encode `text` for a query string.
 *
 * RFC 3986 unreserved characters pass through; everything else (including space)
 * becomes %XX with uppercase hex digits.
 * @param text the raw query-parameter name or value.
 * @return the percent-encoded form, safe to place in a request-target.
 * @complexity O(n) over the input length.
 * @alloc allocates the result.
 * @systest RequestsSys.QueryParams
 */
auto percent_encode(builtins::Value auto&& text) {
    auto unreserved = std::string("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~");
    auto hexdigits = std::string("0123456789ABCDEF");
    auto out = std::string("");
    for (auto& ch : text) {
        if (string::contains(unreserved, ch)) {
            out += ch;
        } else {
            auto v = builtins::ord(ch);
            ((out += "%") += builtins::index(hexdigits, builtins::floordiv(v, 16LL))) += builtins::index(hexdigits, builtins::mod(v, 16LL));
        }
    }
    return out;
}


/**
 * Parse one hex chunk-size token (e.g. "1aF").
 *
 * @param text the hex token, both digit cases accepted, no prefix.
 * @return the decoded size, or -1 on a malformed digit. An empty token decodes to 0,
 *         which the chunked framing treats as the final chunk.
 * @complexity O(n) over the token length.
 * @alloc none.
 * @systest RequestsSys.Chunked
 */
auto parse_hex(builtins::Value auto&& text) {
    auto n = 0LL;
    for (auto& ch : text) {
        auto v = builtins::ord(ch);
        if (((v >= 48LL) && (v <= 57LL))) {
            n = ((n * 16LL) + (v - 48LL));
        } else {
            if (((v >= 97LL) && (v <= 102LL))) {
                n = ((n * 16LL) + (v - 87LL));
            } else {
                if (((v >= 65LL) && (v <= 70LL))) {
                    n = ((n * 16LL) + (v - 55LL));
                } else {
                    return (-1LL);
                }
            }
        }
    }
    return n;
}


/**
 * Decode an HTTP/1.1 chunked body.
 *
 * Framing: hex-size line (chunk extensions after `;` ignored), chunk bytes, CRLF,
 * repeated until the 0 chunk. Trailers after the 0 chunk are simply unread.
 * @param raw everything after the response head (the body bytes as received).
 * @param r the Response under construction; `r.error` is set on malformed framing.
 * @return the decoded body, or "" when framing was malformed (see `r.error`).
 * @complexity O(n) over the body length.
 * @alloc allocates the decoded body.
 * @systest RequestsSys.Chunked
 */
auto dechunk(builtins::Value auto&& raw, builtins::Value auto&& r) {
    auto body = std::string("");
    auto pos = 0LL;
    while (true) {
        auto line_end = string::find(builtins::slice(raw, pos, builtins::slice_end), std::string("\r\n"));
        if ((line_end < 0LL)) {
            r.error = std::string("connection closed inside chunked body");
            return std::string("");
        }
        auto size_token = builtins::slice(raw, pos, (pos + line_end));
        auto semi = string::find(size_token, std::string(";"));
        if ((semi >= 0LL)) {
            size_token = builtins::slice(size_token, 0LL, semi);
        }
        auto size = parse_hex(string::strip(size_token));
        if ((size < 0LL)) {
            r.error = std::string("malformed chunk size");
            return std::string("");
        }
        (pos += line_end) += 2LL;
        if ((size == 0LL)) {
            return body;
        }
        if ((builtins::len(raw) < ((pos + size) + 2LL))) {
            r.error = std::string("connection closed inside chunked body");
            return std::string("");
        }
        body += builtins::slice(raw, pos, (pos + size));
        (pos += size) += 2LL;
    }
}


/**
 * Read the whole response from a connected socket (or TLS session for https).
 *
 * Reads every byte until the peer closes — or the socket timeout set by get_once
 * fires, which recv reports as "" (indistinguishable from close by design: we always
 * request `Connection: close`, so EOF IS the end of the response). When @p conn is open
 * the bytes are read (and decrypted) through its TLS session, mirroring the send path;
 * a closed @p conn reads the plain socket.
 * @param fd a connected socket descriptor from socket.tcp_connect.
 * @param conn the owning tls.Conn for https (open), or a closed Conn for plain http.
 * @return all bytes received.
 * @complexity O(n) over the response size.
 * @alloc allocates the received buffer.
 * @systest RequestsSys.BasicGet
 */
auto read_all(builtins::Value auto&& fd, builtins::Value auto&& conn) {
    auto raw = std::string("");
    while (true) {
        auto chunk = std::string("");
        if (conn.is_open()) {
            chunk = conn.recv(65536LL);
        } else {
            chunk = socket::recv(fd, 65536LL);
        }
        if ((builtins::len(chunk) == 0LL)) {
            break;
        }
        raw += chunk;
    }
    return raw;
}


/**
 * Parse a raw HTTP/1.1 response (status line + headers + body) into `r`.
 *
 * Headers land in `r.headers` with LOWERCASED names and stripped values. Body framing
 * precedence: chunked when declared, else Content-Length, else everything to EOF (we
 * always send `Connection: close`). Malformed input sets `r.error` and returns early.
 * @param raw the complete response bytes as received.
 * @param r the Response under construction (status/headers/body/error are filled in).
 * @return `r`, completed or carrying `error`.
 * @complexity O(n) over the response size.
 * @alloc allocates the parsed headers and body.
 * @systest RequestsSys.EofFraming
 * @systest RequestsSys.HeaderLookup
 */
auto parse_response(builtins::Value auto&& raw, builtins::Value auto&& r) {
    auto head_end = string::find(raw, std::string("\r\n\r\n"));
    if ((head_end < 0LL)) {
        r.error = std::string("connection closed before a complete response head");
        return r;
    }
    if ((string::find(raw, std::string("HTTP/")) != 0LL)) {
        r.error = std::string("malformed response head");
        return r;
    }
    auto head = builtins::slice(raw, 0LL, head_end);
    auto line_end = string::find(head, std::string("\r\n"));
    if ((line_end < 0LL)) {
        line_end = builtins::len(head);
    }
    auto space = string::find(head, std::string(" "));
    if (((space < 0LL) || ((space + 4LL) > line_end))) {
        r.error = std::string("malformed status line");
        return r;
    }
    r.status = builtins::to_int(builtins::slice(head, (space + 1LL), (space + 4LL)));
    auto rest = builtins::slice(head, (line_end + 2LL), builtins::slice_end);
    while ((builtins::len(rest) > 0LL)) {
        auto eol = string::find(rest, std::string("\r\n"));
        if ((eol < 0LL)) {
            eol = builtins::len(rest);
        }
        auto line = builtins::slice(rest, 0LL, eol);
        auto colon = string::find(line, std::string(":"));
        if ((colon > 0LL)) {
            auto name = string::lower(string::strip(builtins::slice(line, 0LL, colon)));
            r.headers[name] = string::strip(builtins::slice(line, (colon + 1LL), builtins::slice_end));
        }
        if ((eol == builtins::len(rest))) {
            break;
        }
        rest = builtins::slice(rest, (eol + 2LL), builtins::slice_end);
    }
    auto body = builtins::slice(raw, (head_end + 4LL), builtins::slice_end);
    if ((r.header(std::string("transfer-encoding")) == std::string("chunked"))) {
        r.body = dechunk(body, r);
        return r;
    }
    auto cl = r.header(std::string("content-length"));
    if ((cl != std::string(""))) {
        auto n = builtins::to_int(cl);
        if ((builtins::len(body) < n)) {
            r.error = std::string("connection closed before the complete body arrived");
            return r;
        }
        r.body = builtins::slice(body, 0LL, n);
    } else {
        r.body = body;
    }
    return r;
}


/**
 * One GET exchange against an already-parsed URL (no redirect handling).
 *
 * Connects, applies the timeout, appends `o.params` percent-encoded to the request-target,
 * sends the request (custom headers, default User-Agent, `Connection: close`), then reads
 * and parses the full response. Transport failures come back in `r.error`.
 * @param u the parsed URL (scheme/host/port/target) from parsers.url.
 * @param o per-request options (timeout, params, headers).
 * @param r the Response under construction.
 * @return the completed Response (a non-2xx status is a completed exchange, not an error).
 * @alloc allocates the request and response buffers.
 * @systest RequestsSys.BasicGet
 */
auto get_once(builtins::Value auto&& u, builtins::Value auto&& o, builtins::Value auto&& r) {
    auto fd = socket::tcp_connect(u.host, u.port);
    if ((fd < 0LL)) {
        r.error = (((((std::string("connect to ") + builtins::str(u.host)) + std::string(":")) + builtins::str(u.port)) + std::string(" failed: ")) + builtins::str(socket::last_error()));
        return r;
    }
    auto timeout = o.timeout_ms;
    if ((timeout <= 0LL)) {
        timeout = 30000LL;
    }
    socket::set_timeout(fd, timeout);
    auto conn = tls::Conn();
    if ((u.scheme == std::string("https"))) {
        conn = tls::open(fd, u.host);
        if ((!conn.is_open())) {
            socket::close(fd);
            r.error = (std::string("tls: ") + builtins::str(tls::last_error()));
            return r;
        }
    }
    auto target = u.target;
    auto sep = std::string("?");
    if ((string::find(target, std::string("?")) >= 0LL)) {
        sep = std::string("&");
    }
    for (auto& kv : o.params) {
        (((target += sep) += percent_encode(kv.first)) += "=") += percent_encode(kv.second);
        sep = std::string("&");
    }
    auto req = ((((((std::string("GET ") + builtins::str(target)) + std::string(" HTTP/1.1\r\nHost: ")) + builtins::str(u.host)) + std::string(":")) + builtins::str(u.port)) + std::string("\r\n"));
    for (auto& kv : o.headers) {
        (((req += kv.first) += ": ") += kv.second) += "\r\n";
    }
    if ((!(builtins::contains(o.headers, std::string("user-agent")) || builtins::contains(o.headers, std::string("User-Agent"))))) {
        req += "User-Agent: cheatah-requests/0.2\r\n";
    }
    req += "Connection: close\r\nAccept: */*\r\n\r\n";
    auto sent = 0LL;
    if (conn.is_open()) {
        sent = conn.send(req);
    } else {
        sent = socket::sendall(fd, req);
    }
    if ((sent != 0LL)) {
        conn.close();
        socket::close(fd);
        r.error = std::string("send failed");
        return r;
    }
    auto raw = read_all(fd, conn);
    conn.close();
    socket::close(fd);
    return parse_response(raw, r);
}


/**
 * Perform an HTTP GET, following up to max_redirects 3xx hops.
 *
 * Never raises for network conditions: every failure comes back as a Response with
 * `error` set (and status 0). Redirects (301/302/303/307/308) follow absolute and
 * host-relative Location targets; `https://` is reported in `error` until cheatah TLS
 * lands. Call with a URL alone, or pass Options for params/headers/timeout/redirects.
 * @param url the absolute `http://host[:port]/path[?query]` URL.
 * @param o per-request options; defaults to a 30 s timeout and 5 redirect hops.
 * @return the final Response — check `ok()`, then `status`/`headers`/`body`.
 * @systest RequestsSys.BasicGet
 * @systest RequestsSys.Redirect
 * @systest RequestsSys.RedirectLoop
 */
auto get(builtins::Value auto&& url, builtins::Value auto&& o) {
    auto max_hops = o.max_redirects;
    if ((max_hops <= 0LL)) {
        max_hops = 5LL;
    }
    auto current = url;
    auto hop = 0LL;
    while ((hop <= max_hops)) {
        auto r = Response{.url = static_cast<std::string>(current)};
        auto parser = parsers::url::Parser();
        auto u = parsers::url::Url();
        if ((!parser.parse(current, u))) {
            r.error = (std::string("malformed URL: ") + builtins::str(current));
            return r;
        }
        r = get_once(u, o, r);
        auto redirect = ((r.error == std::string("")) && (((((r.status == 301LL) || (r.status == 302LL)) || (r.status == 303LL)) || (r.status == 307LL)) || (r.status == 308LL)));
        if ((!redirect)) {
            return r;
        }
        auto loc = r.header(std::string("location"));
        if ((loc == std::string(""))) {
            r.error = ((std::string("redirect (") + builtins::str(r.status)) + std::string(") without a Location header"));
            return r;
        }
        if ((string::startswith(loc, std::string("http://")) || string::startswith(loc, std::string("https://")))) {
            current = loc;
        } else {
            if (string::startswith(loc, std::string("/"))) {
                current = (((((builtins::str(u.scheme) + std::string("://")) + builtins::str(u.host)) + std::string(":")) + builtins::str(u.port)) + builtins::str(loc));
            } else {
                r.error = (std::string("unsupported relative redirect Location: ") + builtins::str(loc));
                return r;
            }
        }
        hop += 1LL;
    }
    auto r = Response{.url = static_cast<std::string>(current)};
    r.error = ((std::string("too many redirects (max_redirects = ") + builtins::str(max_hops)) + std::string(")"));
    return r;
}

/**
 * Convenience overload of `get` with the trailing default argument(s) applied.
 * @param url as documented on the primary overload.
 * @return as the primary overload.
 */
static auto get(builtins::Value auto&& url) { return get(url, Options{.timeout_ms = static_cast<long long>(30000LL), .max_redirects = static_cast<long long>(5LL)}); }

/// ABI/identity marker for the `requests` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
/// @return the module name (`"requests"`).
inline const char* module_abi() noexcept { return "requests"; }

}  // namespace cheatah::requests
