// Generated by purrc — do not edit.
#pragma once
#include "cheatah.hpp"

namespace cheatah::parsers {

namespace builtins = ::cheatah::builtins;

/// ABI/identity marker for the `parsers` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
inline const char* module_abi() noexcept { return "parsers"; }

}  // namespace cheatah::parsers
