// Copyright (c) 2026 BigBrain LLC. MIT-licensed (see LICENSE).
// Original work; see ACKNOWLEDGMENTS.md for the open-source ideas we build upon.
#pragma once

#include <string>
#include <vector>

#include "ast.hpp"

// cheatah codegen — AST -> C++ source for a loadable program module.
//
// The emitted translation unit exports `extern "C" void purr_main()`, which the
// cheatah runtime dlopens and calls. Imports become #includes; module
// calls (io.print) become namespace-qualified calls (cheatah::io::
// print). `modules` lists the imported module roots so purrc knows which stdlib
// libraries to link.
namespace cheatah {

struct CodegenResult {
    std::string source;                    // generated C++ (program mode)
    std::string header_source;             // generated header   (library mode)
    std::string impl_source;               // generated impl TU  (library mode, opaque only)
    std::vector<std::string> modules;      // imported module roots (for linking)
    std::vector<std::string> diagnostics;  // empty on success

    bool ok() const { return diagnostics.empty(); }
};

// Program mode: emit one translation unit exporting `purr_main()` (above). When
// @p source_file is non-empty, codegen interleaves `#line N "<source_file>"` directives
// so the C++ backend's diagnostics (and thus the editor's, via `purrc --check`) point at
// the original .purr line rather than the generated C++. Left empty for normal compiles,
// keeping the inspectable .gen.cpp uncluttered. @p remove_unused (the default) drops `let`
// bindings whose variable is never read/printed/returned — preserving a side-effecting
// initializer as a bare expression statement; pass false (purrc's --no-remove-variables) to
// emit every variable verbatim.
// @p base_hoist / @p base_body fold a sibling C++ base (see --base-header) into program output:
// `base_hoist` (its #include/#pragma lines) lands at file scope after the preamble; `base_body` at
// file scope alongside top-level `cpp{}` helpers, so the program body can call it. Both empty by
// default => byte-identical output.
CodegenResult codegen(const Program& program, const std::string& source_file = "",
                      bool remove_unused = true, const std::string& base_hoist = "",
                      const std::string& base_body = "");

// Library mode — emit a `.purr` as an IMPORTABLE cheatah library module living in
// `namespace cheatah::<module_name>` (no purr_main). The result is a HEADER plus, in
// opaque builds, an impl TU compiled into the module's signed static archive:
//
//   transparent (stdlib): the full generated C++ source is inlined into header_source so
//     the true C++ is always visible (impl_source empty);
//   opaque (DEFAULT, external authors): header_source carries only the public API
//     (declarations + the unavoidable templates), and concrete definitions go to
//     impl_source so the implementation is hidden inside the compiled archive.
//
// Templates are header-visible in BOTH modes (a C++ constraint); opacity only conceals
// concretely-typed function bodies.
// The first line of every purrc-generated file. The sibling-fold auto-detect skips any candidate
// base file beginning with this, so a previous generated output is never folded into itself.
inline constexpr const char* kGeneratedMarker = "// Generated by purrc — do not edit.";

struct LibOptions {
    std::string module_name;   // emit into `namespace cheatah::<module_name>`
    bool transparent = false;  // false (default) = opaque; true = source-in-header (stdlib)
    bool remove_unused = true; // drop unused, non-returned locals (a returned var is kept, so
                               // an exported function's result is never removed)
    // A folded sibling C++ base (see --base-header). `base_hoist` is its #include/#pragma/#define
    // lines, emitted at FILE SCOPE before the namespace; `base_body` is the rest, emitted INSIDE
    // `namespace cheatah::<module_name>` BEFORE the transpiled types, so the .purr can call it and
    // it need not see generated structs. Both empty by default => byte-identical output.
    std::string base_hoist;
    std::string base_body;
};
CodegenResult codegen_library(const Program& program, const LibOptions& opts);

} // namespace cheatah
