#include "codegen.hpp"

#include <map>
#include <optional>
#include <set>
#include <sstream>

namespace cheatah {

namespace {

// Bare names that are Python built-ins (always available, no import) -> their C++
// symbol in cheatah::builtins. Keyword-named conversions map specially.
std::optional<std::string> builtin_cpp_name(const std::string& name) {
    static const std::map<std::string, std::string> kBuiltins = {
        {"len", "len"},   {"ord", "ord"},   {"chr", "chr"},     {"hex", "hex"},
        {"oct", "oct"},   {"bin", "bin"},   {"ascii", "ascii"}, {"hash", "hash"},
        {"bool", "to_bool"}, {"int", "to_int"}, {"float", "to_float"},
    };
    const auto it = kBuiltins.find(name);
    if (it == kBuiltins.end()) return std::nullopt;
    return "cheatah::builtins::" + it->second;
}

std::string cpp_string_literal(const std::string& s) {
    std::string out = "\"";
    for (char c : s) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\t': out += "\\t"; break;
            case '\r': out += "\\r"; break;
            default: out += c;
        }
    }
    out += "\"";
    return out;
}

// cheatah type -> C++ type. Primitives, containers (STL), and struct names.
std::string map_type(const TypeRef& t) {
    if (t.name == "int") return "long long";
    if (t.name == "float") return "double";
    if (t.name == "str") return "std::string";
    if (t.name == "bool") return "bool";
    if (t.name == "list" && t.args.size() == 1) {
        return "std::vector<" + map_type(t.args[0]) + ">";
    }
    if (t.name == "dict" && t.args.size() == 2) {
        return "std::unordered_map<" + map_type(t.args[0]) + ", " + map_type(t.args[1]) + ">";
    }
    if (t.name == "array" && t.args.size() == 1 && !t.array_size.empty()) {
        return "std::array<" + map_type(t.args[0]) + ", " + t.array_size + ">";
    }
    return t.name;  // a struct name
}

class Codegen {
public:
    CodegenResult run(const Program& prog) {
        // Pass 1: imports (modules to link) + struct names (for construction syntax).
        for (const StmtPtr& s : prog.body) {
            if (s->kind == StmtKind::Import) {
                const auto& imp = static_cast<const Import&>(*s);
                const std::string key = imp.alias.empty() ? imp.module.front() : imp.alias;
                aliases_[key] = imp.module;
                roots_.insert(imp.module.front());
            } else if (s->kind == StmtKind::StructDef) {
                struct_names_.insert(static_cast<const StructDef&>(*s).name);
            }
        }

        std::ostringstream os;
        os << "// Generated by purrc — do not edit.\n";
        os << "#include <array>\n#include <cmath>\n#include <memory>\n#include <stdexcept>\n"
              "#include <string>\n#include <unordered_map>\n#include <utility>\n#include <vector>\n";
        os << "#include \"runtime.hpp\"\n";
        os << "#include \"builtins.hpp\"\n";  // built-ins are always available
        for (const std::string& root : roots_) {
            os << "#include \"" << root << ".hpp\"\n";
        }
        os << "\n";

        // Struct definitions, then function definitions, at file scope.
        for (const StmtPtr& s : prog.body) {
            if (s->kind == StmtKind::StructDef) gen_struct(os, static_cast<const StructDef&>(*s));
        }
        for (const StmtPtr& s : prog.body) {
            if (s->kind == StmtKind::FnDef) gen_fn(os, static_cast<const FnDef&>(*s));
        }

        // The runtime dlopens this symbol and calls it with a live Runtime.
        os << "extern \"C\" void purr_main(cheatah::runtime::Runtime& cheatah_runtime) {\n";
        os << "    (void)cheatah_runtime;\n";
        for (const StmtPtr& s : prog.body) {
            if (s->kind == StmtKind::Import || s->kind == StmtKind::StructDef ||
                s->kind == StmtKind::FnDef) {
                continue;  // emitted above (imports -> includes)
            }
            gen_stmt(os, *s, "    ");
        }
        os << "}\n";

        CodegenResult r;
        r.source = os.str();
        for (const std::string& root : roots_) r.modules.push_back(root);
        r.diagnostics = std::move(diags_);
        return r;
    }

private:
    void gen_struct(std::ostringstream& os, const StructDef& sd) {
        os << "struct " << sd.name << " {\n";
        for (const Field& f : sd.fields) {
            os << "    " << map_type(f.type) << " " << f.name << ";\n";
        }
        os << "};\n\n";
    }

    void gen_fn(std::ostringstream& os, const FnDef& fd) {
        // `static` -> internal linkage, so the optimizer inlines/optimizes these
        // like local C++ functions (no exported-symbol interposition barrier).
        // Untyped params -> C++20 abbreviated function template (auto params).
        os << "static auto " << fd.name << "(";
        for (std::size_t i = 0; i < fd.params.size(); ++i) {
            os << (i != 0 ? ", " : "") << "auto " << fd.params[i];
        }
        os << ") {\n";
        gen_block(os, fd.body, "    ");
        os << "}\n\n";
    }

    void gen_block(std::ostringstream& os, const Block& block, const std::string& indent) {
        for (const StmtPtr& s : block) gen_stmt(os, *s, indent);
    }

    void gen_stmt(std::ostringstream& os, const Stmt& s, const std::string& indent) {
        switch (s.kind) {
            case StmtKind::Let: {
                const auto& l = static_cast<const Let&>(s);
                os << indent << "auto " << l.name << " = " << gen_expr(*l.value) << ";\n";
                return;
            }
            case StmtKind::Assign: {
                const auto& a = static_cast<const Assign&>(s);
                os << indent << gen_expr(*a.target) << " = " << gen_expr(*a.value) << ";\n";
                return;
            }
            case StmtKind::If: {
                const auto& n = static_cast<const If&>(s);
                os << indent << "if (" << gen_expr(*n.cond) << ") {\n";
                gen_block(os, n.then_body, indent + "    ");
                os << indent << "}";
                if (!n.else_body.empty()) {
                    os << " else {\n";
                    gen_block(os, n.else_body, indent + "    ");
                    os << indent << "}";
                }
                os << "\n";
                return;
            }
            case StmtKind::While: {
                const auto& w = static_cast<const While&>(s);
                os << indent << "while (" << gen_expr(*w.cond) << ") {\n";
                gen_block(os, w.body, indent + "    ");
                os << indent << "}\n";
                return;
            }
            case StmtKind::For:
                gen_for(os, static_cast<const For&>(s), indent);
                return;
            case StmtKind::Return: {
                const auto& r = static_cast<const Return&>(s);
                os << indent << "return" << (r.value ? " " + gen_expr(*r.value) : "") << ";\n";
                return;
            }
            case StmtKind::Try: {
                const auto& t = static_cast<const Try&>(s);
                const std::string exc = (t.catch_var.empty() ? "_purr" : t.catch_var) + "_exc";
                os << indent << "try {\n";
                gen_block(os, t.body, indent + "    ");
                os << indent << "} catch (const std::exception& " << exc << ") {\n";
                if (!t.catch_var.empty()) {
                    os << indent << "    auto " << t.catch_var << " = std::string(" << exc
                       << ".what());\n";
                }
                gen_block(os, t.catch_body, indent + "    ");
                os << indent << "}\n";
                return;
            }
            case StmtKind::Raise:
                os << indent << "throw std::runtime_error("
                   << gen_expr(*static_cast<const Raise&>(s).value) << ");\n";
                return;
            case StmtKind::ExprStmt:
                os << indent << gen_expr(*static_cast<const ExprStmt&>(s).expr) << ";\n";
                return;
            case StmtKind::Import:
            case StmtKind::StructDef:
            case StmtKind::FnDef:
                return;  // emitted at file scope
        }
    }

    void gen_for(std::ostringstream& os, const For& f, const std::string& indent) {
        // Only `for x in range(stop)` / `range(start, stop)` for now (no containers yet).
        if (f.iterable->kind == ExprKind::Call) {
            const auto* call = static_cast<const Call*>(f.iterable.get());
            const Ident* id = call->callee->kind == ExprKind::Ident
                                  ? static_cast<const Ident*>(call->callee.get())
                                  : nullptr;
            if (id != nullptr && id->name == "range") {
                std::string start = "0";
                std::string stop;
                if (call->args.size() == 1) {
                    stop = gen_expr(*call->args[0]);
                } else if (call->args.size() == 2) {
                    start = gen_expr(*call->args[0]);
                    stop = gen_expr(*call->args[1]);
                } else {
                    diags_.push_back("codegen: range() takes 1 or 2 arguments");
                    return;
                }
                os << indent << "for (long long " << f.var << " = " << start << "; " << f.var
                   << " < " << stop << "; ++" << f.var << ") {\n";
                gen_block(os, f.body, indent + "    ");
                os << indent << "}\n";
                return;
            }
        }
        // General container iteration: for x in <list/array/…> -> range-based for.
        os << indent << "for (auto& " << f.var << " : " << gen_expr(*f.iterable) << ") {\n";
        gen_block(os, f.body, indent + "    ");
        os << indent << "}\n";
    }

    std::string module_namespace(const std::vector<std::string>& segs) const {
        std::string ns = "cheatah";
        for (const std::string& s : segs) ns += "::" + s;
        return ns;
    }

    std::optional<std::vector<std::string>> resolve_module_path(const Expr& e) const {
        if (e.kind == ExprKind::Ident) {
            const auto it = aliases_.find(static_cast<const Ident&>(e).name);
            if (it != aliases_.end()) return it->second;
            return std::nullopt;
        }
        if (e.kind == ExprKind::Member) {
            const auto& m = static_cast<const Member&>(e);
            if (auto base = resolve_module_path(*m.object)) {
                base->push_back(m.name);
                return base;
            }
        }
        return std::nullopt;
    }

    std::string gen_expr(const Expr& e) {
        switch (e.kind) {
            case ExprKind::StringLit:
                // Strings are first-class std::string: enables `"a" + "b"` and
                // string containers, and converts freely to string_view.
                return "std::string(" + cpp_string_literal(static_cast<const StringLit&>(e).value) +
                       ")";
            case ExprKind::NumberLit: {
                // cheatah `int` is 64-bit; integer literals -> long long (so a
                // list[int] literal deduces vector<long long>). Floats stay double.
                const auto& n = static_cast<const NumberLit&>(e);
                const bool is_float = n.text.find('.') != std::string::npos ||
                                      n.text.find('e') != std::string::npos ||
                                      n.text.find('E') != std::string::npos;
                return is_float ? n.text : n.text + "LL";
            }
            case ExprKind::BoolLit:
                return static_cast<const BoolLit&>(e).value ? "true" : "false";
            case ExprKind::Ident: {
                const auto it = aliases_.find(static_cast<const Ident&>(e).name);
                return (it != aliases_.end()) ? module_namespace(it->second)
                                              : static_cast<const Ident&>(e).name;
            }
            case ExprKind::Member: {
                const auto& m = static_cast<const Member&>(e);
                if (auto path = resolve_module_path(m)) return module_namespace(*path);
                return gen_expr(*m.object) + "." + m.name;
            }
            case ExprKind::Index: {
                const auto& ix = static_cast<const Index&>(e);
                return gen_expr(*ix.object) + "[" + gen_expr(*ix.index) + "]";
            }
            case ExprKind::Unary: {
                const auto& u = static_cast<const Unary&>(e);
                return "(" + u.op + gen_expr(*u.operand) + ")";
            }
            case ExprKind::Binary: {
                const auto& b = static_cast<const Binary&>(e);
                if (b.op == "**") {  // no C++ infix power -> std::pow
                    return "std::pow(" + gen_expr(*b.lhs) + ", " + gen_expr(*b.rhs) + ")";
                }
                return "(" + gen_expr(*b.lhs) + " " + b.op + " " + gen_expr(*b.rhs) + ")";
            }
            case ExprKind::ListLit: {
                const auto& lst = static_cast<const ListLit&>(e);
                if (lst.elements.empty()) {
                    diags_.push_back("codegen: empty list literal needs a type annotation");
                    return "std::vector<long long>{}";
                }
                return "std::vector{" + gen_args(lst.elements) + "}";  // CTAD -> element type
            }
            case ExprKind::DictLit: {
                const auto& d = static_cast<const DictLit&>(e);
                if (d.keys.empty()) {
                    diags_.push_back("codegen: empty dict literal needs a type annotation");
                    return "std::unordered_map<long long, long long>{}";
                }
                std::string out = "std::unordered_map{";
                for (std::size_t i = 0; i < d.keys.size(); ++i) {
                    out += (i != 0 ? ", " : "");
                    out += "std::pair{" + gen_expr(*d.keys[i]) + ", " + gen_expr(*d.values[i]) + "}";
                }
                return out + "}";
            }
            case ExprKind::Call: {
                const auto& c = static_cast<const Call&>(e);
                if (c.callee->kind == ExprKind::Ident) {
                    const auto& id = static_cast<const Ident&>(*c.callee);
                    if (struct_names_.count(id.name)) {
                        return id.name + "{" + gen_args(c.args) + "}";  // aggregate construction
                    }
                    if (auto bi = builtin_cpp_name(id.name)) {
                        return *bi + "(" + gen_args(c.args) + ")";
                    }
                }
                return gen_expr(*c.callee) + "(" + gen_args(c.args) + ")";
            }
        }
        diags_.push_back("codegen: unsupported expression node");
        return "/* unsupported */";
    }

    std::string gen_args(const std::vector<ExprPtr>& args) {
        std::string out;
        for (std::size_t i = 0; i < args.size(); ++i) {
            out += (i != 0 ? ", " : "") + gen_expr(*args[i]);
        }
        return out;
    }

    std::map<std::string, std::vector<std::string>> aliases_;
    std::set<std::string> roots_;
    std::set<std::string> struct_names_;
    std::vector<std::string> diags_;
};

} // namespace

CodegenResult codegen(const Program& program) { return Codegen().run(program); }

} // namespace cheatah
