#!/usr/bin/env bash
# Build the cheatah docs site — generated BY cheatah. Doxygen is used ONLY as the
# C++ parser: it emits XML (docs/xml), and our own pure-cheatah generator
# (docs/gen-cheatah/gen.purr) renders the modern site into docs/html. The original
# Python generator (docs/gen/generate.py) is kept solely as the gen_bench parity
# benchmark — its output is byte-identical, and the benchmark keeps it that way.
# Serve the site with the VS Code "Open docs in browser" task or scripts/serve-docs.purr.
set -euo pipefail
cd "$(dirname "$0")/.."

DOXYGEN="${DOXYGEN:-doxygen}"
if ! command -v "$DOXYGEN" >/dev/null 2>&1; then
    # fall back to the pinned local install
    DOXYGEN="$HOME/Tools/doxygen-1.16.1/bin/doxygen"
fi

echo "[docs] doxygen (XML)…"
# Clean the XML first: Doxygen does NOT prune stale outputs, so a renamed/removed
# symbol (e.g. a module folded into another) would leave a ghost namespace XML behind
# and leak back into the site + the VS Code hover DB. A from-scratch XML dir avoids that.
rm -rf docs/xml
"$DOXYGEN" Doxyfile

# The toolchain: prefer the release build, fall back to debug.
BIN=build/release/bin
if [ ! -x "$BIN/purrc" ] || [ ! -x "$BIN/cheatah" ]; then
    BIN=build/debug/bin
fi
if [ ! -x "$BIN/purrc" ] || [ ! -x "$BIN/cheatah" ]; then
    echo "[docs] error: build purrc + cheatah first (release or debug preset)" >&2
    exit 1
fi

GEN_SO=build/docs-gen.so
if [ ! -f "$GEN_SO" ] || [ docs/gen-cheatah/gen.purr -nt "$GEN_SO" ] || [ "$BIN/purrc" -nt "$GEN_SO" ]; then
    echo "[docs] compiling the generator (docs/gen-cheatah/gen.purr)…"
    "$BIN/purrc" docs/gen-cheatah/gen.purr -o "$GEN_SO"
fi

echo "[docs] generating site (pure cheatah)…"
rm -rf docs/html
"$BIN/cheatah" "$GEN_SO"

echo "[docs] done -> docs/html/index.html"
