#!/usr/bin/env python3
"""Post-process the generated Doxygen site to match the cheatah theme:
recolor the residual blues (the Graphviz diagrams and a few hardcoded hexes in
doxygen.css) to the warm, earthy palette. Run via docs/build-docs.sh."""
import re
import sys
from pathlib import Path

HTML = Path(__file__).resolve().parent / "html"

# Doxygen's blue diagram/UI hexes -> earthy tan / warm-dark replacements.
SVG_MAP = {
    "#63b8ff": "#d6ad73",   # primary node/edge blue -> tan
    "#a2b4d6": "#b99e78",   # secondary blue -> muted tan
    "#edf0f7": "#2a251d",   # near-white node fill -> warm dark
    "#4665a2": "#9a7c4f",
    "#1f3b5c": "#2a241b",
}
CSS_MAP = {
    "#1982d2": "#d6ad73",
    "#212f4b": "#38322a",
    "#86a9c4": "#cdb083",
    "#4779ac": "#b08a55",
    "#05070c": "#141110",
    "#090d16": "#16130f",
    "#0b101a": "#1b1814",
    # Stock doxygen.css blues that aren't theme variables — recolor to earthy.
    "#90a5ce": "#d6ad73",  # a.el / code symbol links -> tan
    "#a3b4d7": "#cdb083",  # a.codeRef links -> muted tan
    "#121258": "#232a1d",  # dl.test background -> warm olive
    "#4242cf": "#93b06f",  # dl.test border + title -> sage
    "#c0c0da": "#d3e0c0",  # dl.test text -> warm light
    "#163750": "#211c16",  # dl.todo background blue -> warm dark
    "#dcf0fa": "#efe2c9",  # dl.todo text blue-white -> warm
    # navtree.css stock blues (nav backgrounds, borders, selection).
    "#1d2a43": "#211c16",
    "#283a5d": "#2a241b",
    "#4665a2": "#9a7c4f",
    "#101826": "#16130f",
}

def recolor(text, mapping):
    n = 0
    for src, dst in mapping.items():
        pat = re.compile(re.escape(src), re.IGNORECASE)
        text, c = pat.subn(dst, text)
        n += c
    return text, n

# HTML comments that name Doxygen (e.g. the per-page "<!-- Generated by Doxygen -->"
# marker). Stripped from the generated source so the site doesn't advertise the tool;
# the homepage keeps a visible, deliberate credit. Only comments match — visible text
# (and the homepage credit) is untouched.
COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)

def strip_doxygen_comments(text):
    removed = 0
    def repl(m):
        nonlocal removed
        if "doxygen" in m.group(0).lower():
            removed += 1
            return ""
        return m.group(0)
    return COMMENT.sub(repl, text), removed

def main():
    if not HTML.is_dir():
        print(f"postprocess: {HTML} not found — generate the site first (doxygen Doxyfile)", file=sys.stderr)
        return 1
    total = 0
    for svg in HTML.glob("*.svg"):
        text = svg.read_text()
        new, n = recolor(text, SVG_MAP)
        if n:
            svg.write_text(new)
            total += n
    for name in ("doxygen.css", "navtree.css", "tabs.css"):
        css = HTML / name
        if css.exists():
            text = css.read_text()
            new, n = recolor(text, CSS_MAP)
            if n:
                css.write_text(new)
                total += n
    comments = 0
    for html in HTML.glob("*.html"):
        text = html.read_text()
        new, n = strip_doxygen_comments(text)
        if n:
            html.write_text(new)
            comments += n
    # Neutralize the auto-generated graph-legend boilerplate's tool name (precise
    # phrase replacements only — must not touch asset links like doxygen.css).
    legend = HTML / "graph_legend.html"
    if legend.exists():
        t = legend.read_text()
        t = t.replace("graphs that are generated by doxygen",
                      "graphs that are generated by Graphviz")
        t = t.replace("Class not documented with doxygen comments",
                      "Class not documented")
        legend.write_text(t)
    print(f"postprocess: recolored {total} blue references → earthy palette; "
          f"stripped {comments} Doxygen HTML comment(s)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
